# Generated by Django 4.1 on 2023-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques_link', models.CharField(max_length=512)),
                ('question_title', models.CharField(max_length=256)),
            ],
        ),
    ]
